name: Cerberus Consulting
url: https://cerberus-consulting.net
description: IT and Security Consulting

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
